In [1]:
import pandas as pd
import pyreadstat
import os
from pathlib import Path
import re
import functools

In [ ]:
C:\Users\annda\1\Documents\UIS\Nov\default\data_downloaded\MDA_MICS4_2012\microdata

In [18]:
pd.read_pickle('result//COD_MICS6_2017-2018.pkl')

,HH1,HH2,LN,HL4,HL6,ED4,ED6,ED8,ED9,ED15,...,WB5,WB6A,WB6B,WB7,WB9,WB11,WB12A,WB12B,WB14,WMWEIGHT
0,1.0,1.0,1.0,MASC,25,OUI,NON,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,2.0,FEM,20,OUI,NON,OUI,NON,NON,...,OUI,SECONDAIRE 1,2.0,NON,NON,NON,NaN,NaN,NaN,3.283949
2,1.0,1.0,3.0,FEM,69,NON,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,4.0,MASC,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,5.0,MASC,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103417,721.0,30.0,3.0,MASC,13,OUI,NON,OUI,OUI,OUI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103418,721.0,30.0,4.0,FEM,11,OUI,NON,OUI,OUI,OUI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103419,721.0,30.0,5.0,FEM,9,NON,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103420,721.0,30.0,6.0,FEM,7,NON,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103421,721.0,30.0,7.0,MASC,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# df, metadata = pyreadstat.read_sav('data_downloaded//MDA_MICS4_2012//microdata//mn.sav', apply_value_formats=True)
# df_wm, metadata_wm = pyreadstat.read_sav('data_downloaded//MDA_MICS4_2012//microdata//wm.sav', apply_value_formats=True)
# df_hl, metadata_hl = pyreadstat.read_sav('data_downloaded//MDA_MICS4_2012//microdata//hl.sav', apply_value_formats=True)


# ,usecols=['HH1','HH2','HL1','HL7','ED3','ED4A']
my_dict=metadata.column_names_to_labels
df = pd.DataFrame(list(my_dict.items()),columns = ['var','label']) 
df
# metadata_wm.column_names_to_labels

           var                        label
0          HH1               Cluster number
1          HH2             Household number
2           LN                  Line number
3         MWM1               Cluster number
4         MWM2             Household number
..         ...                          ...
167   mmelevel                    Education
168  ethnicity  Ethnicity of household head
169     wscore           Wealth index score
170    windex5       Wealth index quintiles
171   mnweight          Men's sample weight

[172 rows x 2 columns]

In [6]:
df_wm

,HH1,HH2,LN,WM1,WM2,WM3,WMINT,WM4,WM5,WM6D,...,wscoreu,windex5u,windex10u,wscorer,windex5r,windex10r,ListCat,ClustCat,PSU,stratum
0,1.0,3.0,2.0,1.0,3.0,2.0,42.0,40.0,42.0,17.0,...,-1.303378,Poorest,1st decile,NaN,NaN,NaN,With child U5 during listing,11.0,1.0,1.0
1,1.0,4.0,1.0,1.0,4.0,1.0,42.0,40.0,42.0,17.0,...,-7.384811,Poorest,1st decile,NaN,NaN,NaN,With child U5 during listing,11.0,1.0,1.0
2,1.0,5.0,2.0,1.0,5.0,2.0,41.0,40.0,41.0,17.0,...,-0.172666,Second,3rd decile,NaN,NaN,NaN,Without child U5 during listing,12.0,1.0,1.0
3,1.0,5.0,3.0,1.0,5.0,3.0,41.0,40.0,41.0,18.0,...,-0.172666,Second,3rd decile,NaN,NaN,NaN,Without child U5 during listing,12.0,1.0,1.0
4,1.0,7.0,1.0,1.0,7.0,1.0,41.0,40.0,41.0,17.0,...,0.189458,Middle,5th decile,NaN,NaN,NaN,With child U5 during listing,11.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3386,232.0,15.0,4.0,232.0,15.0,4.0,111.0,110.0,111.0,4.0,...,NaN,NaN,NaN,1.057341,Richest,9th decile,With child U5 during listing,2321.0,232.0,16.0
3387,232.0,19.0,2.0,232.0,19.0,2.0,114.0,110.0,114.0,21.0,...,NaN,NaN,NaN,1.196066,Richest,10th decile,With child U5 during listing,2321.0,232.0,16.0
3388,232.0,21.0,2.0,232.0,21.0,2.0,114.0,110.0,114.0,18.0,...,NaN,NaN,NaN,0.783937,Richest,9th decile,With child U5 during listing,2321.0,232.0,16.0
3389,232.0,23.0,2.0,232.0,23.0,2.0,114.0,110.0,114.0,21.0,...,NaN,NaN,NaN,1.061497,Richest,10th decile,Without child U5 during listing,2322.0,232.0,16.0
3390,232.0,23.0,3.0,232.0,23.0,3.0,114.0,110.0,114.0,21.0,...,NaN,NaN,NaN,1.061497,Richest,10th decile,Without child U5 during listing,2322.0,232.0,16.0

In [ ]:
metadata.column_names_to_labels

In [97]:
df_wm['WM17'].unique().tolist()

['COMPLETED',
 '3 VISITS AND RESPONDENT NOT AT HOME',
 'REFUSED',
 'ADULT CONSENT IS NOT GIVEN, MOTHER / CAREGIVER AGE 15-17',
 'PARTLY COMPLETED',
 'INCAPACITATED',
 'OTHER']

In [89]:
# walk through the downloaded files folder, put joined data into a dataframe for each survey
def walk_4_data(datapath):
#   all_obj used to store all the dataframes for all surveys
    all_obj={}
    for root, dirs, files in os.walk(datapath, topdown=False):
        for dire in dirs:
            if (dire =='microdata') &('MICS5' in os.path.join(root, dire)):
                current_dir=os.path.join(root, dire)
#               walk through the SAV files in microdata folder
                for name in os.listdir(current_dir): 
#                       SPSS file path
                    path=os.path.join(current_dir, name)
#                       grandparent folder of the file path, survey_path contains the survey name
                    survey_path=Path(path).parents[1]
#                       Basename is the survey name
                    survey=os.path.basename(survey_path)
                    if name.lower().endswith('hl.sav'):
                        df_hl, metadata_hl = pyreadstat.read_sav(path, apply_value_formats=True,usecols=['HH1','HH2','HL1','HL7','ED3','ED4A'])
                        df_hl.rename(columns={'HL1':'LN'},inplace=True)
                    elif name.lower().endswith('wm.sav'):
#                       Get data from SPSS file and add to dfs
                        df_sex, metadata_sex = pyreadstat.read_sav(path, apply_value_formats=True,usecols=['HH1','HH2','LN','WB3','WB4'])

#                       merge different module lieracy information into one dataframe
                df_final = pd.merge(df_hl,df_sex,how='right',on=['HH1','HH2','LN'])
                df_final2 = df_final[~df_final['WB4'].isna()]
                ed_cats=df_final2['ED4A'].cat.categories
                wb_cats=df_final2['WB4'].cat.categories
                allcats=[]
                allcats.extend(ed_cats)
                allcats.extend(wb_cats)
                for cat in allcats:
                    if cat not in ed_cats:
                        df_final2['ED4A'].cat.add_categories(cat,inplace=True)
                    if cat not in wb_cats:
                        df_final2['WB4'].cat.add_categories(cat,inplace=True)


                if 'ED4A' in df_final2.columns:
                    records=df_final2[df_final2['ED4A']!=df_final2['WB4']].shape[0]
                    if records!=0:
                        print(df_final2[df_final2['ED4A']!=df_final2['WB4']],metadata_hl.column_names_to_labels,metadata_sex.column_names_to_labels)
                else:
                     print('noED3'+survey)

In [90]:
walk_4_data('C://Users//annda//1//Documents//UIS//Nov//default//data_downloaded')

          HH1   HH2   LN HL7 ED3                      ED4A WB3  \
0         1.0   1.0  1.0   1  Si  Universitaria o superior  Si
3         1.0   3.0  2.0   2  Si  Universitaria o superior  Si
4         1.0   4.0  2.0   2  Si  Universitaria o superior  Si
9         1.0   9.0  2.0   2  Si  Universitaria o superior  Si
16        1.0  13.0  2.0   2  Si        Media o secundaria  Si
...       ...   ...  ...  ..  ..                       ...  ..
30218  2083.0   3.0  2.0   2  Si  Universitaria o superior  Si
30219  2083.0   3.0  6.0   6  Si  Universitaria o superior  Si
30223  2083.0   7.0  1.0   1  Si  Universitaria o superior  Si
30230  2083.0  14.0  3.0   3  Si  Universitaria o superior  Si
30231  2083.0  14.0  4.0   4  Si  Universitaria o superior  Si

                            WB4
0      Universitario o superior
3      Universitario o superior
4      Universitario o superior
9      Universitario o superior
16     Universitario o superior
...                         ...
30218  Universitario o superior
30219  Universitario o superior
30223  Universitario o superior
30230  Universitario o superior
30231  Universitario o superior

[8099 rows x 8 columns] {'HH1': 'UPM', 'HH2': 'No. del hogar en la muestra', 'HL1': 'Número de línea', 'HL7': 'Número de línea de la mujer de 15 - 49 años', 'ED3': 'Asistencia a preescolar/escuela', 'ED4A': 'Nivel más alto al que asistió'} {'HH1': 'UPM', 'HH2': 'No. del hogar en la muestra', 'LN': 'Número de línea', 'WB3': 'Alguna vez asistió a la escuela', 'WB4': 'Nivel más alto al que asistió'}
         HH1   HH2   LN HL7  ED3                  ED4A  WB3  \
0        1.0   1.0  3.0   3  Sim            Secondario  Sim
1        1.0   1.0  8.0   8  Sim            Secondario  Sim
5        1.0   3.0  1.0   1  Sim            Secondario  Sim
6        1.0   4.0  3.0   3  Sim            Secondario  Sim
10       1.0   5.0  4.0   4  Sim  Técnico-profissional  Sim
...      ...   ...  ...  ..  ...                   ...  ...
10738  342.0  16.0  7.0   7  Sim            Secondario  Sim
10739  342.0  16.0  8.0   8  Sim            Secondario  Sim
10740  342.0  17.0  2.0   2  Sim            Secondario  Sim
10741  342.0  17.0  5.0   5  Sim            Secondario  Sim
10743  342.0  19.0  4.0   4  Sim            Secondario  Sim

                        WB4
0                Secundário
1                Secundário
5                Secundário
6                Secundário
10     Tecnico-Profissional
...                     ...
10738            Secundário
10739            Secundário
10740            Secundário
10741            Secundário
10743            Secundário

[2171 rows x 8 columns] {'HH1': 'Nº de DR', 'HH2': 'Nº de Agregado familiar', 'HL1': 'Nº de linha', 'HL7': 'Nº de linha se é mulher de 15 - 49 anos', 'ED3': '(Nome) Frequenta uma escola ou jardim de infância?', 'ED4A': 'Qual o nível mais elevado que Qual foi a última classe /ano (nome) frequentou?'} {'HH1': 'Nº de DR', 'HH2': 'Nº de Agregado familiar', 'LN': 'Nº de linha', 'WB3': 'Alguma vez frequentou a escola ou jardim de infância?', 'WB4': 'Qual o nível mais alto que atingiu?'}
         HH1   HH2   LN HL7  ED3                        ED4A  WB3  \
0        1.0   1.0  3.0   3  Yes      Upper secondary(10-11)  Yes
1        1.0   3.0  2.0   2  Yes  Technical and Professional  Yes
4        1.0   3.0  6.0   6  Yes      Upper secondary(10-11)  Yes
8        1.0   7.0  3.0   3  Yes      Upper secondary(10-11)  Yes
10       1.0  14.0  3.0   3  Yes      Upper secondary(10-11)  Yes
...      ...   ...  ...  ..  ...                         ...  ...
12900  840.0  13.0  2.0   2  Yes      Upper secondary(10-11)  Yes
12902  840.0  15.0  4.0   4  Yes  Technical and Professional  Yes
12904  840.0  16.0  3.0   3  Yes      Upper secondary(10-11)  Yes
12906  840.0  18.0  2.0   2  Yes  Technical and Professional  Yes
12909  840.0  20.0  1.0   1  Yes  Technical and Professional  Yes

                            WB4
0      General Secondary(10-11)
1      Technical and Vocational
4      General Secondary(10-11)
8      General Secondary(10-11)
10     General Secondary(10-11)
...                         ...
12900  General Secondary(10-11)
12902  Technical and Vocational
12904  General Secondary(10-11)
12906  Technical and Vocational
12909  Technical and Vocational

[7893 rows x 8 columns] {'HH1': 'Cluster number', 'HH2': 'Household number', 'HL1': 'Line number', 'HL7': 'Line number of woman age 15 - 49', 'ED3': 'Ever attended school or pre-school', 'ED4A': 'Highest level of education attended'} {'HH1': 'Cluster number', 'HH2': 'Household number', 'LN': 'Line number', 'WB3': 'Ever attended school', 'WB4': 'Highest level of school attended'}
         HH1   HH2   LN HL7 ED3                                        ED4A  \
1        1.0   3.0  2.0   2  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
5        1.0   7.0  3.0   3  Si                         BachilleratoGeneral
6        1.0   8.0  3.0   3  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
12       1.0  13.0  2.0   2  Si                         BachilleratoGeneral
14       1.0  16.0  3.0   3  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
...      ...   ...  ...  ..  ..                                         ...
14858  708.0  16.0  2.0   2  Si                         BachilleratoGeneral
14859  708.0  16.0  3.0   3  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
14861  708.0  17.0  3.0   3  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
14862  708.0  18.0  2.0   2  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)
14863  708.0  19.0  2.0   2  Si  Secundaria(Tercer ciclo/  7°, 8°,9° grado)

      WB3                                       WB4
1      Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
5      Si                      Bachillerato General
6      Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
12     Si                      Bachillerato General
14     Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
...    ..                                       ...
14858  Si                      Bachillerato General
14859  Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
14861  Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
14862  Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)
14863  Si  Secundaria (Baja/ Tercer ciclo/7°,8°,9°)

[5165 rows x 8 columns] {'HH1': 'Número de conglomerado', 'HH2': 'Número de hogar', 'HL1': 'Número de lineas', 'HL7': 'Número de línea de la mujer de  15 - 49 años', 'ED3': 'Asistió alguna vez a la escuela', 'ED4A': 'Nivel más alto aprobado'} {'HH1': 'Número de conglomerado', 'HH2': 'Número de hogar', 'LN': 'Numero de linea', 'WB3': 'Asistencia escolar', 'WB4': 'Nivel más alto aprobado'}
       HH1   HH2   LN HL7  ED3         ED4A  WB3          WB4
1178  49.0  22.0  4.0   4  Sim  SecundÃ¡rio  Sim      BÃ¡sico
1569  68.0   1.0  3.0   3  Sim  SecundÃ¡rio  Sim      BÃ¡sico
1760  75.0  24.0  4.0   4  Sim     Superior  Sim  SecundÃ¡rio
1860  80.0  10.0  2.0   2  Sim  SecundÃ¡rio  Sim     Superior
1993  86.0  13.0  6.0   6  Sim  SecundÃ¡rio  Sim      BÃ¡sico {'HH1': 'NÃºmero de Area de EnumeraÃ§Ã£o', 'HH2': 'NÃºmero do Agregado', 'HL1': 'NÃºmero de linha', 'HL7': 'Numero de linha para mulher de  15 - 49 anos', 'ED3': 'Frequenta uma escola ou InstituiÃ§Ã£o prÃ©-escolar', 'ED4A': 'Nivel  mais elavado que atingiu'} {'HH1': 'NÃºmero de Area de EnumeraÃ§Ã£o', 'HH2': 'NÃºmero do Agregado', 'LN': 'NÃºmero de linha', 'WB3': 'JÃ\x81 FREQUENTOU A ESCOLA OU JARDIM-DE-INFÃ‚NCIA/CRECHE', 'WB4': 'QUAL Ã‰ O NÃ\x8dVEL ESCOLAR MAIS ALTO QUE ATINGIU'}
        HH1   HH2   LN HL7  ED3                 ED4A  WB3  \
701    35.0  13.0  6.0   6  Yes  Professional School  Yes
3167  165.0  11.0  4.0   4  Yes      Upper Secondary  Yes
4012  214.0   1.0  5.0   5  Yes      Lower Secondary  Yes
4013  214.0   1.0  6.0   6  Yes      Upper Secondary  Yes
4095  217.0   6.0  2.0   2  Yes      Upper Secondary  Yes
4199  222.0  17.0  6.0   6  Yes              Primary  Yes
5733  295.0   7.0  3.0   3  Yes      Upper Secondary  Yes
7237  366.0  17.0  1.0   1  Yes      Upper Secondary  Yes
7482  378.0  11.0  4.0   4  Yes              Primary  Yes

                             WB4
701   College/University & above
3167             Lower Secondary
4012             Upper Secondary
4013             Lower Secondary
4095             Lower Secondary
4199             Lower Secondary
5733             Lower Secondary
7237             Lower Secondary
7482             Lower Secondary   {'HH1': 'Cluster number', 'HH2': 'Household number', 'HL1': 'Line number', 'HL7': 'Line number of woman age 15 - 49', 'ED3': 'Ever attended school or pre-school', 'ED4A': 'Highest level of education attended'} {'HH1': 'Cluster number', 'HH2': 'Household number', 'LN': 'Line number', 'WB3': 'Ever attended school', 'WB4': 'Highest level of school attended'}

In [67]:
df_o, metadata_o = pyreadstat.read_sav('data_downloaded//SLV_MICS5_2014//microdata//wm.sav', apply_value_formats=True)
df_HL, metadata_HL = pyreadstat.read_sav('data_downloaded//SLV_MICS5_2014//microdata//hl.sav', apply_value_formats=True)

pd.merge(df_HL,df_o,left_on=['HH1','HH2','HL1'],right_on=['HH1','HH2','LN'],how='right').loc[:,['ED3','WB3']]

      ED3 WB3
0      Si  Si
1      Si  Si
2      Si  Si
3      Si  Si
4      Si  Si
...    ..  ..
14860  Si  Si
14861  Si  Si
14862  Si  Si
14863  Si  Si
14864  Si  Si

[14865 rows x 2 columns]

In [92]:
 metadata_HL.column_names_to_labels

{'HH1': 'Número de conglomerado',
 'HH2': 'Número de hogar',
 'HL1': 'Número de lineas',
 'HL3': 'Parentesco con el Jefe',
 'HL4': 'Sexo',
 'HL5M': 'Mes de Nacimiento',
 'HL5Y': 'Año de Nacimiento',
 'HL6': 'Edad',
 'HL7': 'Número de línea de la mujer de  15 - 49 años',
 'HL7B': 'Número de línea de niños 0-4',
 'HL11': 'Está viva la madre',
 'HL12': 'Número de Línea de la madre  HH',
 'HL12A': 'Donde vive la madre natural',
 'HL13': 'Está vivo el padre',
 'HL14': 'Número de línea del Padre natural',
 'HL14A': 'Donde vive el padre natural',
 'HL15': 'Número de línea de la cuidadora primaria',
 'ED1': 'Número de línea',
 'ED3': 'Asistió alguna vez a la escuela',
 'ED4A': 'Nivel más alto aprobado',
 'ED4B': 'Grado más alto aprobado',
 'ED5': 'Durante el actual año escolar (2014), asistió  a la escuela o universidad',
 'ED6A': 'Durante ese año a qué nivel estuvo asistiendo',
 'ED6B': 'Durante ese año a qué grado escolar estuvo asistiendo',
 'ED7': 'Durante el año escolar anterior asistió a la escuela preescolar',
 'ED8A': 'Durante el año escolar anterior a qué nivel asistió',
 'ED8B': 'Durante el año escolar anterior a qué grado asistió',
 'HH5D': 'Día de la entrevista',
 'HH5M': 'Mes de la entrevista',
 'HH5Y': 'Año de la entrevista',
 'HH6': 'Área',
 'HH7': 'Región',
 'HH7A': 'Departamento',
 'MLINE': 'Número de línea de la madre',
 'FLINE': 'Número de línea del padre',
 'religion': 'Religión del Jefe de Hogar',
 'helevel': 'Educación del jefe del hogar',
 'melevel': 'Educación de la madre',
 'felevel': 'Educación del padre',
 'schage': 'Edad al inicio del año escolar',
 'hhweight': 'Ponderación del hogar',
 'wscore': 'Combined wealth score',
 'windex5': 'Quintiles del índice de riqueza',
 'wscoreu': 'Urban wealth score',
 'windex5u': 'Quintiles del índice de riqueza Urbano',
 'wscorer': 'Rural wealth score',
 'windex5r': 'Quintiles del índice de riqueza Rural'}

In [8]:
'M'<'N'

True

In [46]:
df_wm['WB3'].cat.add_categories("Missing",inplace=True)
df_wm['WB4'].cat.add_categories("Missing",inplace=True)

In [26]:
merge2=df_merge.loc[df_merge['WB3'].isna(),['HH1','HH2','LN']]

In [28]:
metadata_wm2.column_names_to_labels

{'HH1': 'Número de cluster',
 'HH2': 'Número de hogar',
 'LN': 'Line number',
 'WM4': 'Número de línea de la mujer',
 'WM6D': 'Día de la entrevista',
 'WM6M': 'Mes de la entrevista',
 'WM6Y': 'Año de la entrevista',
 'WM7': 'Resultado de la entrevista de mujer',
 'WM10H': 'Inicio de la entrevista - Hora',
 'WM10M': 'Inicio de la entrevista - Minutos',
 'WM11H': 'Final de la entrevista - Hora',
 'WM11M': 'Final de la entrevista - Minutos',
 'CONSENT_WM': 'Consentimiento para entrevista',
 'WB1M': 'Mes de nacimiento de la mujer',
 'WB1Y': 'Año de nacimiento de la mujer',
 'WB2': 'Edad de la mujer',
 'WB3': 'Ha asistido al pre-escolar o a la escuela',
 'WB4': 'Nivel más alto al que ha asistido',
 'WB5': 'Grado más alto que ha completado',
 'WB7': 'Puede leer la frase',
 'MT2': 'Frecuencia con que lee periódico o revista',
 'MT3': 'Frecuencia con que escucha la radio',
 'MT4': 'Frecuencia con que ve televisión',
 'MT6': 'Usó computadora alguna vez',
 'MT7': 'Uso de computadora en los últimos12 meses',
 'MT7A': 'Razón no usó computadora en los últimos12 meses',
 'MT8': 'Frecuencia uso de computadora en el último mes',
 'MT9': 'Usó internet alguna vez',
 'MT10': 'Usó internet en los últimos12 meses',
 'MT10A': 'Razón por la que no utilizó internet en los últimos12 meses',
 'MT10BA': 'Recibo y envío de correo',
 'MT10BB': 'Participar en redes sociales',
 'MT10BC': 'Leer o descargar noticias o periódicos',
 'MT10BD': 'Interacción con organizaciones gubernamentales',
 'MT10BE': 'Obtener información sobre productos o servicios',
 'MT10BF': 'Compra, venta o contratación de bienes o servicios',
 'MT10BG': 'Operaciones de banca electrónica',
 'MT10BH': 'Buscar o participar en actividades de educación formal o capacitación',
 'MT10BI': 'Buscar información sobre temas de salud',
 'MT10BJ': 'Descargar software, entretenimiento u otros',
 'MT11': 'Frecuencia uso de internet en el último mes',
 'CM1': 'Ha dado a luz alguna vez',
 'CM12D': 'Día del último parto',
 'CM12M': 'Mes del último parto',
 'CM12Y': 'Año del último parto',
 'CM13': 'Último parto en los dos últimos años',
 'DB1': 'Quería quedar embarazada',
 'DB2': 'Quería tener un hijo más adelante o no quería tener más hijos',
 'DB3U': 'Tiempo que quería esperar (unidad)',
 'DB3N': 'Tiempo que quería esperar (número)',
 'MN1': 'Tuvo control prenatal',
 'MN2A': 'Control prenatal: Médico',
 'MN2B': 'Control prenatal: Enfermera',
 'MN2C': 'Control prenatal: Auxiliar de Enfermera',
 'MN2G': 'Control prenatal: Promotor de la Salud',
 'MN2E': 'Control prenatal: Comadrona',
 'MN2F': 'Control prenatal: Partera tradicional',
 'MN2H': 'Control prenatal: Parientes, amigo(a)',
 'MN2I': 'Control prenatal: Curandero/Hierbero',
 'MN2J': 'Control prenatal: Médico Tradicional Indígena',
 'MN2X': 'Control prenatal: Otro',
 'MN3': 'Número de controles prenatales',
 'MN4A': 'Presión arterial',
 'MN4B': 'Muestra de orina',
 'MN4C': 'Muestra de sangre',
 'MN17A': 'Asistencia en el parto: Médico',
 'MN17B': 'Asistencia en el parto: Enfermera',
 'MN17C': 'Asistencia en el parto: Auxiliar de Enfermera',
 'MN17G': 'Asistencia en el parto: Promotor de la Salud',
 'MN17E': 'Asistencia en el parto: Comadrona',
 'MN17F': 'Asistencia en el parto: Partera tradicional',
 'MN17H': 'Asistencia en el parto: Pariente/Amigo(a)',
 'MN17I': 'Asistencia en el parto: Curandero/Hierbero',
 'MN17J': 'Asistencia en el parto: Médico Tradicional Indígena',
 'MN17X': 'Asistencia en el parto: Otro',
 'MN17Y': 'Asistencia en el parto: Nadie',
 'MN18': 'Lugar del parto',
 'MN19': 'Nacimiento por cesárea',
 'MN20': 'Tamaño al nacer',
 'MN21': 'Fue pesado al nacer',
 'MN22A': 'Peso de tarjeta o memoria',
 'MN22': 'Peso (kilogramos)',
 'MN23': 'Volvió el período menstrual después del nacimiento',
 'MN24': 'Dió pecho',
 'MN25U': 'Cuanto tiempo después del nacimiento le dió pecho (unidades)',
 'MN25N': 'Cuanto tiempo después del nacimiento le dió pecho (números)',
 'MN26': 'En los 3 días después del parto se le dió algo que no fuera leche materna',
 'MN27A': 'Bebida dada al niño: Leche (no materna)',
 'MN27B': 'Bebida dada al niño: Agua sola (sin aditivos)',
 'MN27C': 'Bebida dada al niño: Agua con azucar o glucosa',
 'MN27D': 'Bebida dada al niño: Solución medicinal para aliviar cólicos en bebés',
 'MN27E': 'Bebida dada al niño: Solución de agua con azucar y sal',
 'MN27F': 'Bebida dada al niño: Jugo de frutas',
 'MN27G': 'Bebida dada al niño: Fórmula para bebés',
 'MN27H': 'Bebida dada al niño: Té/Infusiones',
 'MN27I': 'Bebida dada al niño: Miel',
 'MN27X': 'Bebida dada al niño: Otro',
 'PN2U': 'Tiempo después del parto (unidad)',
 'PN2N': 'Tiempo después del parto (número)',
 'PN3': 'Evaluaron el bebé antes de se fuera',
 'PN4': 'Evaluaron su condición de salud antes de que se fuera',
 'PN5': 'Examinaron al bebé después que se fuera',
 'PN7': 'Examiraron el bebé después del parto y antes de que se marchara',
 'PN8': 'Examinaron su salud antes de que se marchara',
 'PN9': 'Examinaron el bebé después de que se marchara',
 'PN10': 'Examinaron el bebé después del nacimiento',
 'PN11': 'Veces que lo examinaron',
 'PN12U': 'Tiempo después del parto de la primera revisión (unidad)',
 'PN12N': 'Tiempo después del parto de la primera revisión (número)',
 'PN13A': 'Chequeó la salud: Médico',
 'PN13B': 'Chequeó la salud: Enfermera',
 'PN13C': 'Chequeó la salud: Auxiliar de Enfermera',
 'PN13G': 'Chequeó la salud: Promotor de la Salud',
 'PN13E': 'Chequeó la salud: Comadrona',
 'PN13F': 'Chequeó la salud: Partera tradicional',
 'PN13H': 'Chequeó la salud: Parientes, amigo(a)',
 'PN13I': 'Chequeó la salud: Curandero/Hierbero',
 'PN13J': 'Chequeó la salud: Médico Tradicional Indígena',
 'PN13X': 'Chequeó la salud: Otro',
 'PN14': 'Lugar del chequeo',
 'PN16': 'Chequearon su salud después de que se marchara',
 'PN18': 'Examinaron su salud después del parto y que se fuera',
 'PN19': 'Después del nacimiento alguien la chequeó a usted',
 'PN20': 'Veces que la chequearon',
 'PN21U': 'Tiempo del chequeo después del parto (unidad)',
 'PN21N': 'Tiempo del chequeo después del parto (número)',
 'PN22A': 'Chequeó la salud: Médico',
 'PN22B': 'Chequeó la salud: Enfermera',
 'PN22C': 'Chequeó la salud: Auxiliar de Enfermera',
 'PN22G': 'Chequeó la salud: Promotor de la Salud',
 'PN22E': 'Chequeó la salud: Comadrona',
 'PN22F': 'Chequeó la salud: Partera tradicional',
 'PN22H': 'Chequeó la salud: Parientes, amigo(a)',
 'PN22I': 'Chequeó la salud: Curandero/Hierbero',
 'PN22J': 'Chequeó la salud: Médico Tradicional Indígena',
 'PN22X': 'Chequeó la salud: Otro',
 'PN23': 'Lugar del chequeo',
 'IS2A': 'Síntomas: Si el niño no puede beber o mamar',
 'IS2B': 'Síntomas: Si se pone más enfermo',
 'IS2C': 'Síntomas: Si le da fiebre',
 'IS2D': 'Síntomas: Si tiene respiraciones rápidas',
 'IS2E': 'Síntomas: Si tiene dificultad para respirar',
 'IS2F': 'Síntomas: Si hace deposiciones/heces con sangre',
 'IS2G': 'Síntomas: Si bebe poco',
 'IS2H': 'Síntomas: Si tiene alergia',
 'IS2I': 'Síntomas: Si tiene vómito',
 'IS2J': 'Síntomas: Si tiene diarrea',
 'IS2X': 'Síntomas: Otro',
 'IS2Y': 'Síntomas: Otro',
 'IS2Z': 'Síntomas: Otro',
 'CP1': 'Embarazada',
 'CP2': 'Actualmente usando un método para evitar el embarazo',
 'CP2A': 'En el pasado ha usado un método para evitar el embarazo',
 'CP3A': 'Método actual: Salpin/Operación o esterilización femenina',
 'CP3B': 'Método actual: Operación masculina',
 'CP3C': 'Método actual: DIU',
 'CP3D': 'Método actual: Inyecciones',
 'CP3E': 'Método actual: Implantes',
 'CP3F': 'Método actual: Píldoras',
 'CP3G': 'Método actual: Condón masculino',
 'CP3H': 'Método actual: Condón femenino',
 'CP3I': 'Método actual: Diafragma',
 'CP3J': 'Método actual: Jalea/Espuma',
 'CP3K': 'Método actual: Amenorrea por lactancia (MELA)',
 'CP3L': 'Método actual: Abstinencia periódica (Ritmo)',
 'CP3M': 'Método actual: Retiro',
 'CP3X': 'Método actual: Otro',
 'UN2': 'Quería quedar embarazada',
 'UN3': 'Quería tener un hijo más adelante',
 'UN4': 'Le gustaría tener otro hijo',
 'UN6': 'Le gustaría tener un/otro hijo',
 'UN7U': 'Tiempo que quisiera esperar: Unidad',
 'UN7N': 'Tiempo que quisiera esperar: Número',
 'UN10': 'Físicamente capaz de quedar embarazada',
 'UN11A': 'Razón no quedar embarazada: Relaciones sexuales infrecuentes',
 'UN11B': 'Razón no quedar embarazada: Menopausia',
 'UN11C': 'Razón no quedar embarazada: Nunca menstruó',
 'UN11D': 'Razón no quedar embarazada: Histerectomía',
 'UN11E': 'Razón no quedar embarazada: Ha intentado sin resultados',
 'UN11F': 'Razón no quedar embarazada: Amenorrea postparto',
 'UN11G': 'Razón no quedar embarazada: Amamantamiento',
 'UN11H': 'Razón no quedar embarazada: Muy vieja',
 'UN11I': 'Razón no quedar embarazada: Fatalista',
 'UN11X': 'Razón no quedar embarazada: Otro',
 'UN11Z': 'Razón no quedar embarazada: No sabe',
 'UN13U': 'Tiempo de su último periodo menstrual: Unidad',
 'UN13N': 'Tiempo de su último periodo menstrual: Número',
 'DV1A': 'Justifica que el esposo golpee a la esposa: Si ella sale sin avisarle',
 'DV1B': 'Justifica que el esposo golpee a la esposa: Si ella descuida a los niños',
 'DV1C': 'Justifica que el esposo golpee a la esposa: Si ella discute con él',
 'DV1D': 'Justifica que el esposo golpee a la esposa: Si ella se niega a tener relaciones sexuales con él',
 'DV1E': 'Justifica que el esposo golpee a la esposa: Si ella quema la comida',
 'DV1F': 'Justifica que el esposo golpee a la esposa: Si ella viste provocativamente',
 'MA1': 'Actualmente casada o unida con un hombre',
 'MA2': 'Edad de la pareja',
 'MA3': 'Tiene su esposo/pareja otras esposas/parejas',
 'MA4': 'Número de esposas/parejas',
 'MA5': 'Ha estado alguna vez casada o unida con un hombre',
 'MA6': 'Estado civil actual',
 'MA7': 'Casada o unida una o más veces',
 'MA8M': 'Mes en que se unió o casó por primera vez',
 'MA8Y': 'Año en que se unió o casó por primera vez',
 'MA9': 'Edad cuando comenzó a vivir con su primer esposo/pareja',
 'SB1': 'Edad cuando tuvo la primera relación sexual',
 'SB2': 'Utilizó condón la primera vez que tuvo relaciones sexuales',
 'SB3U': 'Última vez que tuvo relaciones sexuales (unidades)',
 'SB3N': 'Última vez que tuvo relaciones sexuales (números)',
 'SB4': 'Utilizó condón la última vez que tuvo relaciones sexuales',
 'SB5': 'Relación que tenía con la persona con quien tuvo relaciones sexuales la última vez',
 'SB7': 'Edad de la persona con quien tuvo la última relación sexual',
 'SB8': 'Ha tenido relaciones sexuales con otra persona en los últimos 12 meses',
 'SB9': 'Utilizó condón la última que tuvo relaciones sexuales con esa persona',
 'SB10': 'Relación que tenía con la otra pareja sexual',
 'SB12': 'Edad de la otra persona',
 'SB13': 'Sexo con otra persona en los últimos 12 meses',
 'SB14': 'Número de parejas sexuales en los últimos 12 meses',
 'SB15': 'Número de parejas sexuales en toda su vida',
 'HA1': 'Ha oído hablar sobre el SIDA',
 'HA2': 'Se puede reducir el riesgo de contraer SIDA teniendo una sola relación sexual que no tenga SIDA ni otra parejas',
 'HA3': 'Se puede contagiar de SIDA por brujería o medios sobrenaturales',
 'HA4': 'Pueden las personas reducir el riesgo de contraer SIDA usando condones',
 'HA5': 'Pueden las personas contagiarse con el virus del SIDA a través de un mosquito',
 'HA6': 'Pueden las personas contagiarse con SIDA por compartir la comida con una persona infectada',
 'HA7': 'Es posible que una persona que parezca saludable tenga el virus del SIDA',
 'HA8A': 'Puede el virus del SIDA ser transmitido de la madre al hijo durante el embarazo',
 'HA8B': 'Puede el virus del SIDA ser transmitido de la madre al hijo durante el parto',
 'HA8C': 'Puede el virus del SIDA ser transmitido de la madre al hijo mientras está lactando/amamantando',
 'HA9': 'Si una profesora tiene el virus del SIDA pero no está enferma se debe permitir que dé clases',
 'HA10': 'Le compraría verduras frescas a una persona con SIDA',
 'HA11': 'Si un familiar suyo se contagiara con SIDA querría que permaneciera en secreto',
 'HA12': 'Si un familiar suyo se contagiara con SIDA estaría dispuesto/a a cuidar de él/ella',
 'HA15A': 'Información en chequeo prenatal: bebés que se infectan',
 'HA15B': 'Información en chequeo prenatal: lo que puede hacer para evitar contagiarse con el virus del SIDA',
 'HA15C': 'Información en chequeo prenatal: información para hacerse prueba del SIDA',
 'HA15D': 'Información en chequeo prenatal: ofreció hacerle prueba del SIDA',
 'HA16': 'Se hizo prueba de SIDA como chequeo prenatal',
 'HA17': 'Recibió los resultados de la prueba del SIDA',
 'HA18': 'Recibió consejería después de la prueba',
 'HA20': 'Se le realizó la prueba del SIDA entre el momento de llegada para el parto y el momento del parto',
 'HA21': 'Recibió los resultados de la prueba',
 'HA22': 'Le han hecho otra prueba de SIDA desde la que se realizó durante el embarazo',
 'HA23': 'Cuando fue la última vez que se realizó la prueba del SIDA',
 'HA24': 'Se le realizó alguna vez la prueba del SIDA',
 'HA25': 'Cuando fue la última vez que se realizó la prueba del SIDA',
 'HA26': 'Recibió los resultados de esta prueba',
 'HA27': 'Conoce un lugar donde la gente puede ir para hacerse una prueba del SIDA',
 'LS2': 'Felicidad y satisfacción',
 'LS3': 'Satisfacción con su vida familiar',
 'LS4': 'Satisfacción con sus amistades',
 'LS5': 'Asistió a la escuela en el 2012',
 'LS6': 'Satisfacción con la escuela',
 'LS7': 'Satisfacción con su trabajo actual',
 'LS8': 'Satisfacción con su salud',
 'LS9': 'Satisfacción con el lugar donde vive',
 'LS10': 'Satisfacción con el trato de la gente',
 'LS11': 'Satisfacción con su apariencia',
 'LS12': 'Satisfacción con su vida en general',
 'LS13': 'Satisfacción con sus ingresos actuales',
 'LS14': 'Condición de vida con relación al año pasado',
 'LS15': 'Condición de vida en un año',
 'HH3': 'Número de encuestadora',
 'HH4': 'Número de supervisor',
 'HH6': 'Area',
 'HH7': 'Provincia o Comarca',
 'WDOI': 'Fecha de entrevista de la mujer (CMC)',
 'WDOB': 'Fecha de nacimiento de la mujer (CMC)',
 'WAGE': 'Edad',
 'WDOM': 'Fecha de matrimonio o unión (CMC)',
 'WAGEM': 'Edad al primer matrimonio/unión',
 'WDOBLC': 'Fecha de nacimiento del último hijo (CMC)',
 'MSTATUS': 'Estado marital',
 'welevel': 'Educación',
 'ethnicity': 'Grupo étnico del jefe del hogar',
 'wmweight': 'Peso muestral de las mujeres (poblacionales)',
 'zwmweight': 'Peso muestral de las mujeres (normalizados)',
 'wscore': 'Combined wealth score',
 'windex5': 'Quintiles del índice de riqueza',
 'wscoreu': 'Urban wealth score',
 'windex5u': 'Quintiles del índice de riqueza Urbano',
 'wscorer': 'Rural wealth score',
 'windex5r': 'Quintiles del índice de riqueza Rural'}

In [32]:
# df_wm2, metadata_wm2 = pyreadstat.read_sav('data_downloaded//PAN_MICS5_2013//microdata//wm.sav', apply_value_formats=True)
# missing=pd.merge(df_wm2,merge2,how='inner',on=['HH1','HH2','LN'])
missing['WB3'].unique()

[NaN]
Categories (0, object): []

In [47]:
df_merge=pd.merge(df,df_wm,how='right',left_on=['HH1','HH2','HL7'],right_on=['HH1','HH2','LN'])
df_merge=df_merge[~df_merge['WB3'].isna()]
df_merge[df_merge['ED3']!=df_merge['WB3']]

Empty DataFrame
Columns: [HH1, HH2, HL1, HL7, ED3, ED4A, LN, WB3, WB4]
Index: []

In [44]:
df_merge['WB3'].cat.categories

Index(['No', 'Sí', 'missing'], dtype='object')

In [41]:
df['ED3'].unique()

[Sí, NaN, No, Missing]
Categories (3, object): [Sí, No, Missing]